name: Python Package Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: List directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Pickle_Test/analysis directory contents:"
        ls -la Pickle_Test/analysis/
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert pytest
        if [ -f "Pickle_Test/requirements.txt" ]; then
          pip install -r Pickle_Test/requirements.txt
        fi
    
    - name: Run notebook test
      run: |
        cd Pickle_Test
        # Convert notebook to Python script
        jupyter nbconvert --to python analysis/pickle_test_suite.ipynb
        
        # Run the script and capture its output
        if python analysis/pickle_test_suite.py; then
          echo "✅ Notebook executed successfully"
          exit 0
        else
          echo "❌ Notebook execution failed"
          exit 1
        fi
