name: Python Package Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: List directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Pickle_Test directory contents:"
        ls -la Pickle_Test/
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert pytest
        if [ -f "Pickle_Test/requirements.txt" ]; then
          pip install -r Pickle_Test/requirements.txt
        fi
    
    - name: Test with pytest
      run: |
        # First check if the notebook exists
        if [ ! -f "Pickle_Test/pickle_test_suite.ipynb" ]; then
          echo "Error: pickle_test_suite.ipynb not found in Pickle_Test directory"
          echo "Available files in Pickle_Test directory:"
          ls -la Pickle_Test/
          exit 1
        fi
        
        # Convert notebook to Python script and run tests
        cd Pickle_Test
        jupyter nbconvert --to python pickle_test_suite.ipynb
        pytest pickle_test_suite.py -v
